package com.JackZ.BestForum.model;

import java.util.Date;

public class Advertisement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.title
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.url
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.image
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.gmt_start
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Date gmtStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.gmt_end
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Date gmtEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.gmt_create
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.gmt_modified
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.status
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.position
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.id
     *
     * @return the value of advertisement.id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.id
     *
     * @param id the value for advertisement.id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.title
     *
     * @return the value of advertisement.title
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.title
     *
     * @param title the value for advertisement.title
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.url
     *
     * @return the value of advertisement.url
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.url
     *
     * @param url the value for advertisement.url
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.image
     *
     * @return the value of advertisement.image
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.image
     *
     * @param image the value for advertisement.image
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.gmt_start
     *
     * @return the value of advertisement.gmt_start
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Date getGmtStart() {
        return gmtStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.gmt_start
     *
     * @param gmtStart the value for advertisement.gmt_start
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setGmtStart(Date gmtStart) {
        this.gmtStart = gmtStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.gmt_end
     *
     * @return the value of advertisement.gmt_end
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Date getGmtEnd() {
        return gmtEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.gmt_end
     *
     * @param gmtEnd the value for advertisement.gmt_end
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setGmtEnd(Date gmtEnd) {
        this.gmtEnd = gmtEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.gmt_create
     *
     * @return the value of advertisement.gmt_create
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.gmt_create
     *
     * @param gmtCreate the value for advertisement.gmt_create
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.gmt_modified
     *
     * @return the value of advertisement.gmt_modified
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.gmt_modified
     *
     * @param gmtModified the value for advertisement.gmt_modified
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.status
     *
     * @return the value of advertisement.status
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.status
     *
     * @param status the value for advertisement.status
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.position
     *
     * @return the value of advertisement.position
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.position
     *
     * @param position the value for advertisement.position
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setPosition(String position) {
        this.position = position;
    }
}