package com.JackZ.BestForum.model;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.source
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.link
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.pub_date
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Date pubDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.view_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.like_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.comment_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.gmt_latest_comment
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Date gmtLatestComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.status
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.column
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Integer column;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.gmt_craete
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Date gmtCraete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.gmt_modified
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.source
     *
     * @return the value of news.source
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.source
     *
     * @param source the value for news.source
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.link
     *
     * @return the value of news.link
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.link
     *
     * @param link the value for news.link
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.pub_date
     *
     * @return the value of news.pub_date
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.pub_date
     *
     * @param pubDate the value for news.pub_date
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.view_count
     *
     * @return the value of news.view_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.view_count
     *
     * @param viewCount the value for news.view_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.like_count
     *
     * @return the value of news.like_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.like_count
     *
     * @param likeCount the value for news.like_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.comment_count
     *
     * @return the value of news.comment_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.comment_count
     *
     * @param commentCount the value for news.comment_count
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.gmt_latest_comment
     *
     * @return the value of news.gmt_latest_comment
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Date getGmtLatestComment() {
        return gmtLatestComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.gmt_latest_comment
     *
     * @param gmtLatestComment the value for news.gmt_latest_comment
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setGmtLatestComment(Date gmtLatestComment) {
        this.gmtLatestComment = gmtLatestComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.status
     *
     * @return the value of news.status
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.status
     *
     * @param status the value for news.status
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.column
     *
     * @return the value of news.column
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Integer getColumn() {
        return column;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.column
     *
     * @param column the value for news.column
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setColumn(Integer column) {
        this.column = column;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.gmt_craete
     *
     * @return the value of news.gmt_craete
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Date getGmtCraete() {
        return gmtCraete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.gmt_craete
     *
     * @param gmtCraete the value for news.gmt_craete
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setGmtCraete(Date gmtCraete) {
        this.gmtCraete = gmtCraete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.gmt_modified
     *
     * @return the value of news.gmt_modified
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.gmt_modified
     *
     * @param gmtModified the value for news.gmt_modified
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}