package com.JackZ.BestForum.model;

public class NewsWithBLOBs extends News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.description
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.html
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String html;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.description
     *
     * @return the value of news.description
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.description
     *
     * @param description the value for news.description
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.html
     *
     * @return the value of news.html
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.html
     *
     * @param html the value for news.html
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setHtml(String html) {
        this.html = html;
    }
}