package com.JackZ.BestForum.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notifier_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Long notifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.receiver_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Long receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.outer_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Long outerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.outer_name
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String outerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notificationtype
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Integer notificationtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.gmt_create
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.status
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notifier_id
     *
     * @return the value of notification.notifier_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Long getNotifierId() {
        return notifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notifier_id
     *
     * @param notifierId the value for notification.notifier_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setNotifierId(Long notifierId) {
        this.notifierId = notifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.receiver_id
     *
     * @return the value of notification.receiver_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.receiver_id
     *
     * @param receiverId the value for notification.receiver_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.outer_id
     *
     * @return the value of notification.outer_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Long getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.outer_id
     *
     * @param outerId the value for notification.outer_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setOuterId(Long outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.outer_name
     *
     * @return the value of notification.outer_name
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getOuterName() {
        return outerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.outer_name
     *
     * @param outerName the value for notification.outer_name
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setOuterName(String outerName) {
        this.outerName = outerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notificationtype
     *
     * @return the value of notification.notificationtype
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Integer getNotificationtype() {
        return notificationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notificationtype
     *
     * @param notificationtype the value for notification.notificationtype
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setNotificationtype(Integer notificationtype) {
        this.notificationtype = notificationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.gmt_create
     *
     * @return the value of notification.gmt_create
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.gmt_create
     *
     * @param gmtCreate the value for notification.gmt_create
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.status
     *
     * @return the value of notification.status
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.status
     *
     * @param status the value for notification.status
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}