package com.JackZ.BestForum.model;

public class UserInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.user_id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.real_name
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.description
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.birthday
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.marriage
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.gender
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.blood_type
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String bloodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.figure
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String figure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.constellation
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String constellation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.education
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.occupation
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String occupation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.location
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.user_id
     *
     * @return the value of user_information.user_id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.user_id
     *
     * @param userId the value for user_information.user_id
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.real_name
     *
     * @return the value of user_information.real_name
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.real_name
     *
     * @param realName the value for user_information.real_name
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.description
     *
     * @return the value of user_information.description
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.description
     *
     * @param description the value for user_information.description
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.birthday
     *
     * @return the value of user_information.birthday
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.birthday
     *
     * @param birthday the value for user_information.birthday
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.marriage
     *
     * @return the value of user_information.marriage
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.marriage
     *
     * @param marriage the value for user_information.marriage
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.gender
     *
     * @return the value of user_information.gender
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.gender
     *
     * @param gender the value for user_information.gender
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.blood_type
     *
     * @return the value of user_information.blood_type
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.blood_type
     *
     * @param bloodType the value for user_information.blood_type
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.figure
     *
     * @return the value of user_information.figure
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getFigure() {
        return figure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.figure
     *
     * @param figure the value for user_information.figure
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setFigure(String figure) {
        this.figure = figure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.constellation
     *
     * @return the value of user_information.constellation
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.constellation
     *
     * @param constellation the value for user_information.constellation
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.education
     *
     * @return the value of user_information.education
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.education
     *
     * @param education the value for user_information.education
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.occupation
     *
     * @return the value of user_information.occupation
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.occupation
     *
     * @param occupation the value for user_information.occupation
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.location
     *
     * @return the value of user_information.location
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.location
     *
     * @param location the value for user_information.location
     *
     * @mbg.generated Sat Oct 10 18:58:09 CST 2020
     */
    public void setLocation(String location) {
        this.location = location;
    }
}