package com.JackZ.BestForum.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String qqAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.baidu_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String baiduAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weibo_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String weiboAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.token
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modified
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.priority
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.score
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_id
     *
     * @return the value of user.account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_id
     *
     * @param accountId the value for user.account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_account_id
     *
     * @return the value of user.qq_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getQqAccountId() {
        return qqAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_account_id
     *
     * @param qqAccountId the value for user.qq_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setQqAccountId(String qqAccountId) {
        this.qqAccountId = qqAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.baidu_account_id
     *
     * @return the value of user.baidu_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getBaiduAccountId() {
        return baiduAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.baidu_account_id
     *
     * @param baiduAccountId the value for user.baidu_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setBaiduAccountId(String baiduAccountId) {
        this.baiduAccountId = baiduAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weibo_account_id
     *
     * @return the value of user.weibo_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getWeiboAccountId() {
        return weiboAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weibo_account_id
     *
     * @param weiboAccountId the value for user.weibo_account_id
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setWeiboAccountId(String weiboAccountId) {
        this.weiboAccountId = weiboAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.token
     *
     * @return the value of user.token
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.token
     *
     * @param token the value for user.token
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_create
     *
     * @return the value of user.gmt_create
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_create
     *
     * @param gmtCreate the value for user.gmt_create
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_modified
     *
     * @return the value of user.gmt_modified
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_modified
     *
     * @param gmtModified the value for user.gmt_modified
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_url
     *
     * @return the value of user.avatar_url
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_url
     *
     * @param avatarUrl the value for user.avatar_url
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.priority
     *
     * @return the value of user.priority
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.priority
     *
     * @param priority the value for user.priority
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.score
     *
     * @return the value of user.score
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.score
     *
     * @param score the value for user.score
     *
     * @mbg.generated Mon Oct 12 17:03:04 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}